repository_prometheus: "prometheus-community https://prometheus-community.github.io/helm-charts"
repository_state_metrics: "kube-state-metrics https://kubernetes.github.io/kube-state-metrics"
repository_grafana: "grafana https://grafana.github.io/helm-charts"
ns_name: "monitoring"
deploy_prometheus: "prometheus --namespace=monitoring --set alertmanager.persistentVolume.enabled=false,server.persistentVolume.enabled=false prometheus-community/prometheus"
deploy_grafana: "grafana -n monitoring --set=adminUser=admin,adminPassword=admin,service.type=NodePort grafana/grafana"