- name: Adds Prometheus Helm Repository
  shell: helm repo add {{ item }}
  with_items:
  - "{{ repository_prometheus }}"
  - "{{ repository_state_metrics }}"
  - "{{ repository_grafana }}"

- name: Updates Helm Repository
  shell: helm repo update

- name: Updates Helm Repository
  shell: kubectl create namespace {{ ns_name }}

- name: Install Prometheus
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_result

- name: Install Grafana
  shell: helm install {{ deploy_grafana }}
  register: grafana_result